export default {
    ContentText: {
      Serial: "STT",
      FixedAssetCode: "Mã tài sản",
      FixedAssetName: "Tên tài sản",
      FixedAssetCategory: "Loại tài sản",
      FixedAssetCategoryCode: "Mã loại tài sản",
      FixedAssetCategoryName: "Tên loại tài sản",
      Department: "Bộ phận sử dụng",
      DepartmentCode: "Mã phận sử dụng",
      DepartmentName: "Bộ phận sử dụng",
      Quantity: "Số lượng",
      Cost: "Nguyên giá",
      LifeTime: "Số năm sử dụng",
      DepreciationRate: "Tỷ lệ hao mòn (%) ",
      ValueAtrophyYear: "Giá trị hao mòn năm",
      TrackedYear: "Năm theo dõi",
      BuyDate: "Ngày mua",
      UseStartDate: "Ngày bắt đầu sử dụng",
      Accumulated: "HM/KH lũy kế",
      ResidualValue: "Giá trị còn lại",
      Feature: "Chức năng",
      Sum: "Tổng số: ",
      Record: "bản ghi",
      red: "*",
      UpdateAsset: "Sửa tài sản",
      AddAsset: "Thêm tài sản",
      Save: "Lưu",
      Cancer: "Hủy",
      Confirm: "Xác nhận",
      NotNull: "không được để trống",
      ConfirmDelete: "Xác nhận xóa các tài sản đã chọn",
      NotValueDelete: "Hãy chọn ít nhất một tài sản",
      Validate: "Vui lòng nhập trường này",
      AddFall: "Thêm mới thất bại",
      Loading: "loading",
    },
    Tooltip: {
      SerialTooltip: "Số thứ tự",
      AccumulatedTooltip: "Hao mòn khấu hao lũy kế",
      DeleteTooltip: "Xóa",
      ExportTooltip: "Xuất khẩu",
      Notify: "Thông báo",
      Menu: "Menu",
      Suport: "Hỗ trợ",
      MyInfor: "Thông tin cá nhân",
      Close: "Đóng"
    },
    Placeholder: {
      SearchAsset: "Tìm kiếm tài sản",
      CategoryAsset: "Loại tài sản",
      Department: "Bộ phận sử dụng",
      ImportAssetCode: "Nhập mã tài sản",
      ImportAssetName: "Nhập tên tài sản",
      ImportDepartmentCode: "Mã bộ phận sử dụng",
      ImportCategoryAssetCode: "Mã loại tài sản",
    },
    Title: {
      AddAsset: "+ Thêm tài sản",
      ListAsset: "Danh sách tài sản",
      FinancialDepartment: "Sở tài chính",
      Year: "Năm",
      DeleteSuccessful: "Xóa dữ liệu thành công",
      SaveSuccessful: "Lưu dữ liệu thành công",
    }
  };